apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-weather-frontend
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-weather-frontend
spec:
  hosts:
  - "*"
  gateways:
  - gw-weather-frontend
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: weather-frontend
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-weather-backend
spec:
  hosts:
    - weather-backend
  http:
  - route:
    - destination:
        host: weather-backend
        subset: single
        port:
          number: 5000
      weight: 50
    - destination:
        host: weather-backend
        subset: multiple
        port:
          number: 5000
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-weather-backend
spec:
  host: weather-backend
  subsets:
  - name: single
    labels:
      version: single
  - name: multiple
    labels:
      version: multiple
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-openweathermap
spec:
  hosts:
  - api.openweathermap.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-googleapis
spec:
  hosts:
  - "accounts.google.com"
  - "*.googleapis.com"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-metadata
spec:
  hosts:
  - metadata.google.internal
  addresses:
  - 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL